Name: Kevin Corder, PhD Student
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
